/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frm_info extends javax.swing.JFrame {

    public static String tema;
    String nombre;
    frm_principal principal;
    frm_test test;

    public frm_info() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    public frm_info(String tema) {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        principal = new frm_principal();
        this.tema = tema;
        lbl_tema.setText("Test de " + tema);
        this.nombre = principal.nombre;
        lbl_nombre.setText("Bienvenido " + nombre);

        if (tema.equalsIgnoreCase("Java")) {
            text_area.setText(" Java es un lenguaje de programacion con POO\n"
                    + " java es simple, seguro y portable. Java es robusto y\n"
                    + " tiene una arquitectura neutral.\n"
                    + " Por ultimo java es interpretado y dinamico.");
        } else if (tema.equalsIgnoreCase("Phyton")) {
            text_area.setText(" Phyton es un lenguaje de programacion interpretado\n"
                    + " tiene un tipado dinamico, y es multiplataforma\n"
                    + " e multiparadigma con orientacion a objetos\n"
                    + " en phyton el formato de codigo es estructurado.");
        } else if (tema.equalsIgnoreCase("Javascript")) {
            text_area.setText(" Javascript es un lenguaje de programacion del cliente\n"
                    + " es un lenguaje orientado a objetos con un tipado debil\n"
                    + " o de por si no tipado.\n"
                    + " javascript es de alto nivel e interpretado.");
        } else if (tema.equalsIgnoreCase("C#")) {
            text_area.setText(" C# es un lenguaje de programacion con sintaxis sencilla\n"
                    + " tiene una orientacion a componentes y a eventos\n"
                    + " es un sistema de tipo unificado CLR\n"
                    + " Usa polimorfismo y operadores sobrescrito");
        } else if (tema.equalsIgnoreCase("C++")) {
            text_area.setText(" C++ es un lenguaje de programacion fuertemente tipado\n"
                    + " tiene una sintaxis heredada del lenguaje C\n"
                    + " c++ tiene un estandard ISO conocido como ANSI-C++\n"
                    + " Soporta programacion orientada a objetos.");
        }
        test = new frm_test();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbl_tema = new javax.swing.JLabel();
        lbl_nombre = new javax.swing.JLabel();
        btn_iniciar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        text_area = new javax.swing.JTextArea();
        btn_volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_tema.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        lbl_tema.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lbl_tema.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_developer_40px.png"))); // NOI18N
        jPanel1.add(lbl_tema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 330, 37));

        lbl_nombre.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(lbl_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 76, 200, 33));

        btn_iniciar.setText("Iniciar test");
        btn_iniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_iniciar.setBorderPainted(false);
        btn_iniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_iniciar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_iniciarMouseExited(evt);
            }
        });
        btn_iniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_iniciarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 260, 210, 50));

        text_area.setEditable(false);
        text_area.setBackground(new java.awt.Color(204, 204, 204));
        text_area.setColumns(20);
        text_area.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        text_area.setRows(5);
        text_area.setText("\n");
        text_area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_area.setSelectionColor(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(text_area);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 120, 417, -1));

        btn_volver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_arrow_30px.png"))); // NOI18N
        btn_volver.setBorderPainted(false);
        btn_volver.setContentAreaFilled(false);
        btn_volver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_volver.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_back_arrow_40px.png"))); // NOI18N
        btn_volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_volverActionPerformed(evt);
            }
        });
        jPanel1.add(btn_volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(495, 6, 40, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_iniciarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseEntered
        btn_iniciar.setBackground(new Color(0, 0, 0));
        btn_iniciar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_iniciarMouseEntered

    private void btn_iniciarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_iniciarMouseExited
        btn_iniciar.setBackground(new Color(240, 240, 240));
        btn_iniciar.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_iniciarMouseExited

    private void btn_iniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_iniciarActionPerformed
        test.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_iniciarActionPerformed

    private void btn_volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_volverActionPerformed
        principal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btn_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_iniciar;
    private javax.swing.JButton btn_volver;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_nombre;
    private javax.swing.JLabel lbl_tema;
    private javax.swing.JTextArea text_area;
    // End of variables declaration//GEN-END:variables
}
