/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class frm_principal extends javax.swing.JFrame {

    public static String javak, py, js, c1, c2, nombre;

    public frm_principal() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_java = new javax.swing.JButton();
        btn_py = new javax.swing.JButton();
        btn_js = new javax.swing.JButton();
        btn_c1 = new javax.swing.JButton();
        btn_c2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                formMouseDragged(evt);
            }
        });
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                formMousePressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_developer_40px.png"))); // NOI18N
        jLabel1.setText("Lenguajes de programacion");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, -1, -1));

        btn_java.setText("Java");
        btn_java.setBorder(null);
        btn_java.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_java.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_javaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_javaMouseExited(evt);
            }
        });
        btn_java.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_javaActionPerformed(evt);
            }
        });
        jPanel1.add(btn_java, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 90, 40));

        btn_py.setText("Phyton");
        btn_py.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_py.setBorderPainted(false);
        btn_py.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_py.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pyMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pyMouseExited(evt);
            }
        });
        btn_py.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pyActionPerformed(evt);
            }
        });
        jPanel1.add(btn_py, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 90, 40));

        btn_js.setText("Javascript");
        btn_js.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_js.setBorderPainted(false);
        btn_js.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_js.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_jsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_jsMouseExited(evt);
            }
        });
        btn_js.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jsActionPerformed(evt);
            }
        });
        jPanel1.add(btn_js, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 90, 40));

        btn_c1.setText("C#");
        btn_c1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_c1.setBorderPainted(false);
        btn_c1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_c1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_c1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_c1MouseExited(evt);
            }
        });
        btn_c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c1ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_c1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 90, 40));

        btn_c2.setText("C++");
        btn_c2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btn_c2.setBorderPainted(false);
        btn_c2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_c2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_c2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_c2MouseExited(evt);
            }
        });
        btn_c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_c2ActionPerformed(evt);
            }
        });
        jPanel1.add(btn_c2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 90, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_30px.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_delete_40px_1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(535, 7, 30, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_javaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_javaActionPerformed
        nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        if (!(nombre.equals(""))) {
            javak = btn_java.getText().trim();
            frm_info info = new frm_info(javak);
            info.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        }
    }//GEN-LAST:event_btn_javaActionPerformed

    private void btn_pyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pyActionPerformed
        nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        if (!(nombre.equals(""))) {
            py = btn_py.getText().trim();
            frm_info info = new frm_info(py);
            info.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        }

    }//GEN-LAST:event_btn_pyActionPerformed

    private void btn_jsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jsActionPerformed
        nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        if (!(nombre.equals(""))) {
            js = btn_js.getText().trim();
            frm_info info = new frm_info(js);
            info.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        }

    }//GEN-LAST:event_btn_jsActionPerformed

    private void btn_c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c1ActionPerformed
        nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        if (!(nombre.equals(""))) {
            c1 = btn_c1.getText().trim();
            frm_info info = new frm_info(c1);
            info.setVisible(true);
            this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        }

    }//GEN-LAST:event_btn_c1ActionPerformed

    private void btn_c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_c2ActionPerformed
        nombre = JOptionPane.showInputDialog(this,"Ingrese su nombre");
        if (!(nombre.equals(""))) {
            c2 = btn_c2.getText().trim();
            frm_info info = new frm_info(c2);
            info.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(this, "Debe ingresar un nombre");
        }

    }//GEN-LAST:event_btn_c2ActionPerformed

    private void btn_javaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_javaMouseEntered
        btn_java.setBackground(new Color(0, 0, 0));
        btn_java.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_javaMouseEntered

    private void btn_javaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_javaMouseExited
        btn_java.setBackground(new Color(240, 240, 240));
        btn_java.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_javaMouseExited

    private void btn_pyMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pyMouseEntered
        btn_py.setBackground(new Color(0, 0, 0));
        btn_py.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_pyMouseEntered

    private void btn_pyMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pyMouseExited
        btn_py.setBackground(new Color(240, 240, 240));
        btn_py.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_pyMouseExited

    private void btn_jsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jsMouseEntered
        btn_js.setBackground(new Color(0, 0, 0));
        btn_js.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_jsMouseEntered

    private void btn_jsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_jsMouseExited
        btn_js.setBackground(new Color(240, 240, 240));
        btn_js.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_jsMouseExited

    private void btn_c1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c1MouseEntered
        btn_c1.setBackground(new Color(0, 0, 0));
        btn_c1.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_c1MouseEntered

    private void btn_c1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c1MouseExited
        btn_c1.setBackground(new Color(240, 240, 240));
        btn_c1.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_c1MouseExited

    private void btn_c2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c2MouseEntered
        btn_c2.setBackground(new Color(0, 0, 0));
        btn_c2.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btn_c2MouseEntered

    private void btn_c2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_c2MouseExited
        btn_c2.setBackground(new Color(240, 240, 240));
        btn_c2.setForeground(new Color(0, 0, 0));
    }//GEN-LAST:event_btn_c2MouseExited

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed
    int x, y;
    private void formMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_formMousePressed

    private void formMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseDragged
        int xx = evt.getXOnScreen();
        int xy = evt.getYOnScreen();

        this.setLocation(xx - x, xy - y);
    }//GEN-LAST:event_formMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_c1;
    private javax.swing.JButton btn_c2;
    private javax.swing.JButton btn_java;
    private javax.swing.JButton btn_js;
    private javax.swing.JButton btn_py;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
